<script type="text/javascript" src="<?php echo $this->bootstrapJS ?>"></script>
<link rel="stylesheet" href="<?php echo $this->bootstrapCSS ?>" />

<style>
    body{background-color: #7F7F7F!important}

    #lw_fe_inputelement_lw_formular_template{width: 800px;height: 600px;}
    #tabs ul li a{color: #fff;}

    .activeline {background: #e8f2ff !important;}

    .active{background-color: #777;}

    .description {
        margin-bottom:60px;
        border:1px solid #aaa;
        border-radius: 5px;
        background-color:#eee;
        padding:10px;
    }

    legend.lwadminform {
        height: 20px;
        margin-bottom: 2px;
        line-height: 20px;
        width: 260px;
    }
    html body div#lwContent div {
        font-size: 12px!important;
    }

    fieldset.lwadminform {
        position: relative;
    }


    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center form#gotoform input#gotoid {
        width: 45px;
        margin-bottom: 0;
    }
    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center {
        height: 35px;
    }    


    #container_plugin_bionrw_news{
        background-color: #fff;
        border: 1px solid #bbb;
        border-radius: 10px;
        padding: 10px;
    }

    #container_plugin_bionrw_news #myform .control-group input{
        height: 30px;
        width: 50px;
    }
    #container_plugin_bionrw_news #myform .control-group select{width: 330px;}
    
    #teaseroptions{display: none;}
</style>

<fieldset class="lwadminform">

    <legend class="lwadminform">BIO.NRW Events Basisdaten bearbeiten</legend>
    <div id="container_plugin_bionrw_news">
        <!--<div class="description" >
        </div>-->

        <br>
        <?php if ($this->noConfigurationSaved): ?>
            <p>Hinweis : <br>Das Plugin wurde zum ersten mal aufgerufen. Es sind noch keine Einstellungen gespeichert!</p>
        <?php endif; ?>
        <form id="myform" action="<?php echo $this->actionUrl ?>" method="POST" class="form-horizontal">

            <div class="control-group">
                <label class="control-label" for="language">Sprache</label>
                <div class="controls">
                    <select id="language" name="language">
                        <option value="de" <?php if ($this->language == "de"): ?>selected="selected"<?php endif; ?>>Deutsch</option>
                        <option value="en" <?php if ($this->language == "en"): ?>selected="selected"<?php endif; ?>>Englisch</option>
                    </select>
                </div>
            </div>
            <hr>
            <div class="description"><b>Layout der Teaseransicht ist nur f&uuml;r den Teaserbereich optimiert!</b></div>
            <div class="control-group">
                <label class="control-label" for="teaserview">Teaser-Ansicht verwenden ?</label>
                <div class="controls">
                    <input type="checkbox" id="teaserview" name="teaserview" value="1"  <?php if ($this->teaserview): ?> checked="checked" <?php endif; ?>  onclick='
                                if ($("#teaserview").attr("checked")) {
                                    $("#teaseroptions").slideDown();
                                }
                                else {
                                    $("#teaseroptions").slideUp();
                                }'>
                </div>
            </div>

            <div id="teaseroptions">
                <div class="control-group">
                    <label class="control-label" for="teaserelements">Anzahl anzuzeigender Elemente in der Teaser-Ansicht </label>
                    <div class="controls">
                        <select id="teaserelements" name="teaserelements">
                            <option value="1" <?php if ($this->teaserelements == "1"): ?>selected="selected"<?php endif; ?>>1 Element</option>
                            <option value="2" <?php if ($this->teaserelements == "2"): ?>selected="selected"<?php endif; ?>>2 Elemente</option>
                            <option value="3" <?php if ($this->teaserelements == "3"): ?>selected="selected"<?php endif; ?>>3 Elemente</option>
                            <option value="4" <?php if ($this->teaserelements == "4"): ?>selected="selected"<?php endif; ?>>4 Elemente</option>
                            <option value="5" <?php if ($this->teaserelements == "5"): ?>selected="selected"<?php endif; ?>>5 Elemente</option>
                            <option value="6" <?php if ($this->teaserelements == "6"): ?>selected="selected"<?php endif; ?>>6 Elemente</option>
                            <option value="7" <?php if ($this->teaserelements == "7"): ?>selected="selected"<?php endif; ?>>7 Elemente</option>
                            <option value="8" <?php if ($this->teaserelements == "8"): ?>selected="selected"<?php endif; ?>>8 Elemente</option>
                            <option value="9" <?php if ($this->teaserelements == "9"): ?>selected="selected"<?php endif; ?>>9 Elemente</option>
                            <option value="10" <?php if ($this->teaserelements == "10"): ?>selected="selected"<?php endif; ?>>10 Elemente</option>
                        </select>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="teaserview">Kalender verwenden ?</label>
                    <div class="controls">
                        <input type="checkbox" id="teaserview" name="calendar" value="1"  <?php if ($this->calendar): ?> checked="checked" <?php endif; ?>>
                    </div>
                </div>
            </div>
            <br>

            <div style="margin-top:15px;margin-bottom:20px; margin-left:20px;">
                <input class="btn btn-primary" type="submit" value="speichern" onClick="submitForm()" />&nbsp;<input class="btn" type="button" value="abbrechen" onclick="document.location.href = '?obj=content';"/>
            </div>
        </form>
    </div>
</fieldset>